Cyrillic.HR/Cyrillic.HR/Models/TimeTracker/Project.cs
using System.Collections.Generic;
using System.ComponentModel;

namespace Cyrillic.HR.Models.TimeTracker
{
    public class Project
    {
        //Model Properties
        public int Id { get; set; }
        [DisplayName("Project Name")]
        public string Name { get; set; }

        //Navigation Properties
        public ICollection<ProjectTask> ProjectTasks { get; set; }

        [DisplayName("Client")]
        public int ClientId { get; set; }
        public Client Client { get; set; }
    }
}

Cyrillic.HR/Cyrillic.HR/Controllers/ProjectController.cs
using Cyrillic.HR.Models;
using Cyrillic.HR.Models.TimeTracker;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Cyrillic.HR.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Project
        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.Client);
            return View(projects.ToList());
        }

        // GET: Project/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name");
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ClientId")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", project.ClientId);
            return View(project);
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", project.ClientId);
            return View(project);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ClientId")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", project.ClientId);
            return View(project);
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cyrillic.HR/Cyrillic.HR/Controllers/TimeTrackerHandlerController.cs
using System.Linq;
using System.Web.Mvc;
using Cyrillic.HR.Models;
using Cyrillic.HR.ViewModels.TimeTracker;

namespace Cyrillic.HR.Controllers
{
    [Authorize]
    public class TimeTrackerHandlerController : Controller
    {
        public ActionResult Index()
        {
            int numberOfClients;
            int numberOfProjects;
            int numberOfProjectTasks;
            using (var db = new ApplicationDbContext())
            {
                numberOfClients = db.Clients.Count();
                numberOfProjects = db.Projects.Count();
                numberOfProjectTasks = db.ProjectTasks.Count();
            }

            var viewModel = new ManagementViewModel
            {
                NumberOfClients = numberOfClients,
                NumberOfProjects = numberOfProjects,
                NumberOfProjectTasks = numberOfProjectTasks
            };

            return View(viewModel);
        }
    }
}

Cyrillic.HR/Cyrillic.HR/Views/Project/Create.cshtml
@model Cyrillic.HR.Models.TimeTracker.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "ClientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Cyrillic.HR/Cyrillic.HR/Views/Project/Delete.cshtml
@model Cyrillic.HR.Models.TimeTracker.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Cyrillic.HR/Cyrillic.HR/Views/Project/Details.cshtml
@model Cyrillic.HR.Models.TimeTracker.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Cyrillic.HR/Cyrillic.HR/Views/Project/Edit.cshtml
@model Cyrillic.HR.Models.TimeTracker.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "ClientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Cyrillic.HR/Cyrillic.HR/Views/Project/Index.cshtml
@model IEnumerable<Cyrillic.HR.Models.TimeTracker.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @if (User.IsInRole("SysAdmin") || User.IsInRole("OrgAdmin"))
    {
        @Html.ActionLink("Create New", "Create")<span> | </span>
    }
    <a href="@Url.Action("Index", "TimeTrackerHandler")">Back to Manager</a>
</p>
<table class="table table-bordered" id="myTable">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Client.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Client.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>
                    @if (User.IsInRole("SysAdmin") || User.IsInRole("OrgAdmin"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })<span> | </span>
                    }
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                    @if (User.IsInRole("SysAdmin") || User.IsInRole("OrgAdmin"))
                    {
                        <span> | </span>@Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Client.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>Actions</th>
        </tr>
    </tfoot>
</table>
@section styles{
    <link href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet" />
}
@section Scripts{
    <script src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script>
        "use strinct";

        $(document).ready(function () {
            // Initialize DataTable
            var table = $('#myTable').DataTable();

            // Setup - add a text input to each footer cell
            $('#myTable tfoot th').each(function () {
                var title = $(this).text();
                $(this).html('<input style="width: 150px;" class="datatable-input-sm" type="text" placeholder="Search ' + title + '" />');
            });

            // Apply the search
            table.columns().every(function () {
                var that = this;

                $('input', this.footer()).on('keyup change', function () {
                    if (that.search() !== this.value) {
                        that
                            .search(this.value)
                            .draw();
                    }
                });
            });
        });
    </script>
}