Cyrillic.HR/Cyrillic.HR/Controllers/CandidateController.cs
using CandidateEmailHandler;
using Cyrillic.HR.Models;
using Cyrillic.HR.Models.TalentResourceManager;
using Cyrillic.HR.Models.TalentResourceManager.EmailParsing;
using Cyrillic.HR.Models.TalentResourceManager.Skills;
using Cyrillic.HR.ViewModels.TalentResourceManager;
using Microsoft.AspNet.Identity;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace Cyrillic.HR.Controllers
{
    [Authorize]
    public class CandidateController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var candidates = new List<Candidate>();
            var orgs = GetOrganizations();

            foreach (var org in orgs)
            {
                var orgCandidates = GetCandidatesForOrganization(org.Id);

                //check if we are not showing same candidate already for a different org
                foreach (var candidate in orgCandidates)
                {
                    if (!candidates.Contains(candidate))
                    {
                        candidates.Add(candidate);
                    }
                }
            }

            var showCandidatesViewModel = new ShowCandidatesViewModel
            {
                Imported = false,
                Candidates = candidates
            };

            return View(showCandidatesViewModel);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var candidate = db.Candidates.Single(c => c.Id == id);

            db.Candidates.Remove(candidate);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var candidate = db.Candidates.Include(o => o.Organizations).Include(s=>s.Skills).SingleOrDefault(c => c.Id == id);
            var removeOrganizations = GetOrganizations();
            var assignToOrganizations = GetOrganizations();
            var showCandidateOrganizations = candidate.Organizations.Intersect(GetOrganizations());

            //organizations that user can access to, that don`t have candidate already
            foreach (var org in candidate.Organizations)
            {

                assignToOrganizations.Remove(org);
            }

            if (!User.IsInRole("SysAdmin"))
            {
                removeOrganizations.Remove(db.Organizations.SingleOrDefault(x => x.Id == 1));
            }

            var candidateViewModel = new CandidateViewModel
            {
                Candidate = candidate,
                RemoveFromOrganizations = removeOrganizations,
                AssignToOrganizations = assignToOrganizations.ToList(),
                AccessableOrganizations = showCandidateOrganizations.ToList()

            };


            if (User.IsInRole("OrgUser"))
            {
                if (candidate.ApplicationUserId == User.Identity.GetUserId())
                {
                    candidateViewModel.EditableByUser = true;
                }
                else
                {
                    candidateViewModel.EditableByUser = false;
                }
            }
            else
            {
                candidateViewModel.EditableByUser = true;
            }


            var users = new List<ApplicationUser>();
            if (User.IsInRole("OrgAdmin") || User.IsInRole("SysAdmin"))
            {
                foreach (var org in GetOrganizations())
                {
                    users.AddRange(GetOrganizationUsers(org.Id));
                }
            }
            else
            {
                var userId = User.Identity.GetUserId();
                users.Add(db.Users.FirstOrDefault(x => x.Id == userId));
            }

            candidateViewModel.OrgUsers = users;

            return View(candidateViewModel);
        }

        [HttpPost]
        public ActionResult Edit(CandidateViewModel viewModel)
        {
            var addedOrg = db.Organizations.FirstOrDefault(x => x.Id == viewModel.SelectedOrganizationId);
            var removedOrg = db.Organizations.FirstOrDefault(x => x.Id == viewModel.RemovingOrganizationId);

            using (db)
            {
                var candidateToEdit = db.Candidates.Include(o => o.Organizations).SingleOrDefault(c => c.Id == viewModel.Candidate.Id);
                candidateToEdit.FirstName = viewModel.Candidate.FirstName;
                candidateToEdit.LastName = viewModel.Candidate.LastName;
                candidateToEdit.Email = viewModel.Candidate.Email;
                candidateToEdit.JobAppliedTo = candidateToEdit.JobAppliedTo != null ? candidateToEdit.JobAppliedTo : string.Empty;
                candidateToEdit.KeyWords = viewModel.Candidate.KeyWords;

                if (addedOrg != null && !candidateToEdit.Organizations.Contains(addedOrg))
                {
                    candidateToEdit.Organizations.Add(addedOrg);
                }

                if (removedOrg != null && candidateToEdit.Organizations.Contains(removedOrg))
                {
                    if (removedOrg.Id != 1)
                    {
                        candidateToEdit.Organizations.Remove(removedOrg);
                    }

                }
                candidateToEdit.ApplicationUserId = viewModel.AssignedOrgUserId;
                db.SaveChanges();
                db.Dispose();
            }



            return RedirectToAction("Edit", new { id = viewModel.Candidate.Id });
        }


        [HttpGet]
        public ActionResult Create()
        {
            var candidateVievModel = new CandidateViewModel
            {
                AccessableOrganizations = GetOrganizations()
            };

            return View(candidateVievModel);
        }

        [HttpPost]
        public ActionResult Create(CandidateViewModel viewModel)
        {

            var org = new List<Organization>()
            {
                db.Organizations.FirstOrDefault(x=>x.Name =="Global"),
                db.Organizations.FirstOrDefault(x=>x.Id==viewModel.SelectedOrganizationId)
            };
            

            var candidate = new Candidate
            {
                FirstName = viewModel.Candidate.FirstName,
                LastName = viewModel.Candidate.LastName,
                Email = viewModel.Candidate.Email,
                JobAppliedTo = viewModel.Candidate.JobAppliedTo != null ? viewModel.Candidate.JobAppliedTo : string.Empty,
                KeyWords = viewModel.Candidate.KeyWords,
                ImagePath = "DefaultUser.png",
                Organizations = org
            };

            db.Candidates.Add(candidate);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ImportFromEmail()
        {
            var viewModel = new ImportFromEmailViewModel
            {

                EmailProfiles = GetEmailProfilesForOrganizations(),
                Organizations = GetOrganizations()
            };

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult GetCandidates(ImportFromEmailViewModel viewModel)
        {
            var client = new EmailClient();
            var profile = db.EmailProfiles.First(p => p.Id == viewModel.SelectedEmailProfileId);
            foreach (var parsingRule in db.ParsingRules.Where(pr => pr.EmailProfileId == profile.Id))
            {
                profile.ParsingRules.Add(parsingRule);
            }

            var absoluteFolderPath = Path.Combine(HostingEnvironment.ApplicationPhysicalPath, ConfigurationManager.AppSettings["local.resources.trm.candidates.attachments"]);
            client.Connect(profile.Username,
                           profile.Password,
                           ConfigurationManager.AppSettings["mail.client.hostname"],
                           profile.Port,
                          absoluteFolderPath);
            var parser = new EmailParser(client, profile.InboxName);
            var rules = profile.ParsingRules.Select(rule => new ParsingRuleDTO
            {
                EmailField = rule.EmailField,
                IsQualificationRule = rule.IsQualificationRule,
                Regex = rule.Regex,
                CandidateProperty = rule.CandidateProperty
            }).ToList();

            var persons = parser.GetCandidates(rules);

            var showCandidates = new ShowCandidatesViewModel();
            var candidates = new List<Candidate>();
            var orgs = new List<Organization>()
            {
                db.Organizations.FirstOrDefault(o=>o.Id==viewModel.SelectedOrganizationId)
            };
            foreach (var person in persons)
            {
                var candidate = new Candidate();
                var names = GetNames(person.FullName);
                candidate.Organizations = orgs;
                candidate.FirstName = ValidateName(names["FirstName"]);
                candidate.LastName = ValidateName(names["LastName"]);
                candidate.Email = person.Email;
                candidate.JobAppliedTo = person.JobApplied;

                candidates.Add(candidate);
            }
            showCandidates.ImportingOrganizationId = viewModel.SelectedOrganizationId;
            showCandidates.Candidates = candidates;
            showCandidates.Imported = true;

            return View("Index", showCandidates);
        }

        [HttpPost]
        public ActionResult SaveCandidates(ShowCandidatesViewModel viewModel)
        {

            var org = db.Organizations.SingleOrDefault(x => x.Id == viewModel.ImportingOrganizationId);
            var list = new List<Organization>() { org };
            foreach (var candidate in viewModel.Candidates)
            {

Cyrillic.HR/Cyrillic.HR/Views/Shared/CandidatePartialViews/_CandidateDetailsEditable.cshtml
@model Cyrillic.HR.ViewModels.TalentResourceManager.CandidateViewModel
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("GetCandidates", "Candidate", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="form-horizontal">
    <h4>@Model.Candidate.FirstName @Model.Candidate.LastName</h4>
    @if (Model.Candidate.ApplicationUser != null)
    {
        <h5>Assigned to: @Model.Candidate.ApplicationUser.UserName</h5>
    }
    <hr />
    <div class="form-group">
        <label class="control-label col-md-2">First Name</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.FirstName, new { @class = "form-control", placeholder = "First Name", required = "required" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Last Name</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.LastName, new { @class = "form-control", placeholder = "Last Name", required = "required" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Email</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.Email, new { @class = "form-control", placeholder = "Email", required = "required" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Job Applied To</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.JobAppliedTo, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Keywords</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.KeyWords, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Organizations</label>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.SelectedOrganizationId, new SelectList(Model.RemoveFromOrganizations, "Id ", "Name"), new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Assigned To</label>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.AssignedOrgUserId, new SelectList(Model.OrgUsers, "Id ", "UserName"), new { @class = "form-control" })
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
</div>
}

Cyrillic.HR/Cyrillic.HR/Views/Shared/CandidatePartialViews/_CandidateDetailsNonEditable.cshtml
@model Cyrillic.HR.ViewModels.TalentResourceManager.CandidateViewModel
@{
    ViewBag.Title = "Edit";
}



<div class="form-horizontal">
    <h4>@Model.Candidate.FirstName @Model.Candidate.LastName</h4>
    @if (Model.Candidate.ApplicationUser != null)
    {
        <h5>Assigned to: @Model.Candidate.ApplicationUser.UserName</h5>
    }
    <hr />
    <div class="form-group">
        <label class="control-label col-md-2">First Name</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.FirstName, new { @class = "form-control", placeholder = "First Name", required = "required" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Last Name</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.LastName, new { @class = "form-control", placeholder = "Last Name", required = "required" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Email</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.Email, new { @class = "form-control", placeholder = "Email", required = "required" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Job Applied To</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.JobAppliedTo, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Keywords</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Candidate.KeyWords, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Organizations</label>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.SelectedOrganizationId, new SelectList(Model.RemoveFromOrganizations, "Id ", "Name"), new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Assigned To</label>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.AssignedOrgUserId, new SelectList(Model.OrgUsers, "Id ", "UserName"), new { @class = "form-control" })
        </div>
    </div>
</div>

Cyrillic.HR/Cyrillic.HR/Views/Shared/CandidatePartialViews/_CandidateDetailsShowOrganizations.cshtml
@model Cyrillic.HR.ViewModels.TalentResourceManager.CandidateViewModel
@{
    ViewBag.Title = "Edit";
}



<div style="margin-top: 35px;">
    <table class="table-bordered" id="myTable">
        <thead>
            <tr>
                <th>Organization Name</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.AccessableOrganizations.Any())
            {
                foreach (var org in Model.AccessableOrganizations)
                {
                    <tr>
                        <td>@org.Name</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Cyrillic.HR/Cyrillic.HR/Views/Shared/CandidatePartialViews/_CandidateDetailsSkillsModal.cshtml
@model Cyrillic.HR.ViewModels.TalentResourceManager.CandidateViewModel
@{
    ViewBag.Title = "Edit";
}



<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Skills</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@Model.Candidate.FirstName @Model.Candidate.LastName Skills</h4>
            </div>
            <div class="modal-body">
                <div>
                    @if (Model.Candidate.Skills != null && Model.Candidate.Skills.Any())
                    {
                        <table class="table-bordered">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Rating</th>
                                    <th>Years of experience</th>
                                    <th>Skill Level</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var skill in Model.Candidate.Skills)
                                {
                                    <tr>
                                        <td>@skill.Name</td>
                                        <td>@skill.Rating</td>
                                        <td>@skill.YearsExperience</td>
                                        <td>@skill.SkillLevel</td>
                                    </tr>
                                }


                            </tbody>
                        </table>
                    }
                </div>
                @if (Model.EditableByUser)
                {
                    <hr />
                    using (Html.BeginForm("UploadSkills", "Candidate", new { id = Model.Candidate.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        
                        <input type="file" name="FileUpload" />
                        <input type="submit" name="Submit" id="Submit" value="Upload" />
                    }
                }

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

Cyrillic.HR/Cyrillic.HR/Views/Shared/CandidatePartialViews/_CandidateIndexImported.cshtml
@model Cyrillic.HR.ViewModels.TalentResourceManager.ShowCandidatesViewModel

@{
    ViewBag.Title = "Index";
}

@Html.HiddenFor(x => Model.Imported)
<table class="table table-bordered" id="myTable">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Job Applied</th>
            <th>Assigned To</th>

        </tr>
    </thead>
    <tbody>
        @if (Model.Candidates.Any())
        {
            for (var i = 0; i < Model.Candidates.Count; i++)
            {
                <tr>
                    @Html.HiddenFor(x => Model.ImportingOrganizationId)
                    @Html.HiddenFor(x => Model.Candidates[i].ImagePath)
                    <td>@Model.Candidates[i].FirstName</td>
                    @Html.HiddenFor(x => Model.Candidates[i].FirstName)
                    <td>@Model.Candidates[i].LastName</td>
                    @Html.HiddenFor(x => Model.Candidates[i].LastName)
                    <td>@Model.Candidates[i].Email</td>
                    @Html.HiddenFor(x => Model.Candidates[i].Email)
                    <td>@Model.Candidates[i].JobAppliedTo</td>
                    @Html.HiddenFor(x => Model.Candidates[i].JobAppliedTo)
                    @Html.HiddenFor(x => Model.Candidates[i].KeyWords)
                    @Html.HiddenFor(x => Model.Candidates[i].ApplicationUserId)
                    @if (Model.Candidates[i].ApplicationUser != null)
                    {
                        <td>@Model.Candidates[i].ApplicationUser.UserName</td>
                    }
                    else
                    {
                        <td>&nbsp;</td>
                    }
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Job Applied To</th>
            <th>Assigned To</th>
        </tr>
    </tfoot>
</table>
<button type="submit" class="btn btn-primary">Save</button>
<a href="@Url.Action("ImportFromEmail", "Candidate")" class="btn btn-primary">Cancel</a>

Cyrillic.HR/Cyrillic.HR/Views/Shared/CandidatePartialViews/_CandidateIndexNotImported.cshtml
@model Cyrillic.HR.ViewModels.TalentResourceManager.ShowCandidatesViewModel

@{
    ViewBag.Title = "Index";
}

@if (User.IsInRole("SysAdmin") || User.IsInRole("OrgAdmin"))
{
    <p>@Html.ActionLink("Create New", "Create", "Candidate") | @Html.ActionLink("Import From Email", "ImportFromEmail", "Candidate")</p>
}
@Html.HiddenFor(x => Model.Imported)
<table class="table table-bordered" id="myTable">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Job Applied</th>
            <th>Assigned To</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Candidates.Any())
        {
            for (var i = 0; i < Model.Candidates.Count; i++)
            {
                <tr>
                    @Html.HiddenFor(x => Model.Candidates[i].ImagePath)
                    <td>@Model.Candidates[i].FirstName</td>
                    @Html.HiddenFor(x => Model.Candidates[i].FirstName)
                    <td>@Model.Candidates[i].LastName</td>
                    @Html.HiddenFor(x => Model.Candidates[i].LastName)
                    <td>@Model.Candidates[i].Email</td>
                    @Html.HiddenFor(x => Model.Candidates[i].Email)
                    <td>@Model.Candidates[i].JobAppliedTo</td>
                    @Html.HiddenFor(x => Model.Candidates[i].JobAppliedTo)
                    @Html.HiddenFor(x => Model.Candidates[i].KeyWords)
                    @Html.HiddenFor(x => Model.Candidates[i].ApplicationUserId)
                    @if (Model.Candidates[i].ApplicationUser != null)
                    {
                        <td>@Model.Candidates[i].ApplicationUser.UserName</td>
                    }
                    else
                    {
                        <td>&nbsp;</td>
                    }
                    <td>
                        <div class="btn-group">
                            @Html.ActionLink("Details", "Edit", new { controller = "Candidate", id = Model.Candidates[i].Id })
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Job Applied To</th>
            <th>Assigned To</th>
            <th>Actions</th>
        </tr>
    </tfoot>
</table>